version: '3'
services:
  trading-front:
    build: ./trading-front
    container_name: trading-front
    restart: always
    ports:
      - "3000:3000"

  trading-admin:
    build: ./trading-admin
    container_name: trading-admin
    restart: always
    ports:
      - "3001:3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"